---
- name: Setup off-site backups
  become: true
  tags:
    - backup
    - off_site_backup
  block:
    - name: Install cron
      apt:
        name: cron
        update_cache: true

    - name: Configure cron(s) to perform off-site backups
      cron:
        user: "{{ off_site_backup_user }}"
        name: "Off-site backup: {{ item.name }}"
        job: >
          {% set divider = joiner(";") %}
          {% for task in item.tasks %}
          {{ divider() }}
          /usr/sbin/syncoid
          --no-privilege-elevation
          --recursive
          --no-sync-snap
          {% if task.send_options is defined %}
          --sendoptions="{{ task.send_options | join }}"
          {% endif %}
          {{ task.source }}
          {{ task.destination }}
          {% endfor %}
        minute: "{{ item.minute | default('0') }}"
        hour: "{{ item.hour | default('0') }}"
        day: "{{ item.day | default('*') }}"
        month: "{{ item.month | default('*') }}"
        weekday: "{{ item.weekday | default('*') }}"
      loop: "{{ off_site_backup_tasks }}"
      loop_control:
        label: "{{ item.name }}"
