---
- name: Converge
  hosts: all
  tasks:
    - name: "Include joenyland.off_site_backup"
      include_role:
        name: "joenyland.off_site_backup"
      vars:
        off_site_backup_tasks:
          - name: Test
            hour: 1
            minute: 0
            tasks:
              - source: syncoid@server:bpool
                destination: off-site/bpool
