---
- name: Prepare
  hosts: all
  become: true
  tasks:
    # SSH is installed and running by default on a normal Debian system, but not in a Docker image
    - name: Install SSH
      apt:
        name: ssh
        update_cache: true
    # sshd needs to be running for validation of sshd_config
    - name: Start and enable SSH
      service:
        name: ssh
        state: started
        enabled: true
    # User needs to exist
    - name: Create user
      user:
        name: syncoid
        system: true
        password_lock: true
    # ZFS needs to be installed from the contrib repo
    - name: Install contrib repo
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} contrib
        state: present
        filename: contrib
        update_cache: true
